webapp/config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root to: "home#index"
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts, only: [ :index, :new, :create ] do
    member do
      get :like
    end
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

webapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

webapp/app/models/post.rb
class Post < ApplicationRecord
end

webapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

webapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
        redirect_to posts_path
    end
  end
end

webapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def initialize
    @limit = 10
    @user_post = Post.new
    super
  end

  def new
    @user_post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path(limit: @limit)
    else
      flash.now[:alert] = "Failed to share post."
      render "index"
    end
  end

  def index
    # Loald 10 most recent updated posts from posts table
    @limit = params[:limit].to_i || 10
    if @limit < 10
      @limit = 10
    end
    @posts = Post.order(updated_at: :desc).limit(@limit)
    @next_limit = @limit + 10
  end

  def like
    post = Post.find(params[:id])
    post.increment!(:likes) # Increment the likes count
    redirect_to posts_path(limit: @limit)
  end

  private

  def post_params
    username = current_user.username
    w_content = params.require(:post).permit(:content)
    w_content[:username] = username
    w_content
  end
end

webapp/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

webapp/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

webapp/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

webapp/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

webapp/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

webapp/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/helpers/feed_helper.rb
module FeedHelper
end

webapp/app/helpers/home_helper.rb
module HomeHelper
end

webapp/app/views/feed/index.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">User Info</h5>
                    <p class="card-text">@username</p>
                    <p class="card-text">Followers: 123 | Following: 456</p>
                    <button class="btn btn-primary">Edit Profile</button>
                </div>
            </div>
        </div>

        <div class="col-md-6">
          <% @posts.each do |post| %>
            <div class="card mb-3">
              <div class="card-body">
                <%= image_tag "avatar.png", alt: "User Avatar",
                  class: "rounded-circle float-start me-3", style: "width: 50px; height: 50px;" %>
                <h6 class="card-title"><%= post[:username] %></h6>
                <p class="card-text"><%= post[:content] %></p>
                <div class="d-flex justify-content-between">
                    <button class="btn btn-link">Like</button>
                    <button class="btn btn-link">Comment</button>
                    <button class="btn btn-link">Share</button>
                </div>
                </div>
            </div>
        <% end %>
        <a id="bottom"></a>

          <a class="btn btn-primary" href="/feed/index?limit=<%= @next_limit %>#bottom">
            <p style="color: white; text-decoration: none;">Load More</p>
          </a>
        </div>
    </div>
</div>

webapp/app/views/home/index.html.erb
<h1>Welcome to My Rails App!</h1>
<% if user_signed_in? %>
  <p>Hello, <%= current_user.email %>!</p>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_registration_path %> |
  <%= link_to 'Login', new_user_session_path %>
<% end %>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Scroll" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- Optional theme -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item-lg-3">
              <%= link_to 'Home', root_path, :class=>'nav-link'  %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item-lg-3">
                <%= link_to ' Edit Profile ', edit_user_registration_path, :class=>'nav-link' %>
              </li>
              <li class="nav-item-lg-3">
                <%= link_to ' Logout ', destroy_user_session_path, method: :delete, :class=>'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item-lg-3">
                <%= link_to ' Sign Up ', new_user_registration_path, :class=>'nav-link' %>
              </li>
              <li class="nav-item-lg-3">
                <%= link_to ' Login ', new_user_session_path, :class=>'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

webapp/app/views/posts/index.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">User Info</h5>
                    <p class="card-text"><%= current_user.username %></p>
                    <p class="card-text">Followers: 123 | Following: 456</p>
                    <button class="btn btn-primary">Edit Profile</button>
                </div>
            </div>
        </div>

        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% end %>

        <div class="col-md-6">
            <%= form_with model: @user_post, url: posts_path, method: :post do |form| %>
                <%= form.text_area :content, class: "form-control", placeholder: "What's happening?", rows: 3 %>
                <%= form.submit "Tweet", class: "btn btn-primary" %>
            <% end %>
          <% @posts.each do |post| %>
            <div class="card mb-3">
              <div class="card-body">
                <%= image_tag "avatar.png", alt: "User Avatar",
                  class: "rounded-circle float-start me-3", style: "width: 50px; height: 50px;" %>
                <h6 class="card-title"><%= post[:username] %></h6>
                <p class="card-text"><%= post[:content] %></p>
                <div class="d-flex justify-content-between">
                  <%= link_to "Like (#{post.likes || 0})", like_post_path(post[:id]), method: :get, class: "btn btn-link" %>
                </div>
                </div>
            </div>
        <% end %>
        <a id="bottom"></a>

          <a class="btn btn-primary" href="/posts?limit=<%= @next_limit %>#bottom">
            <p style="color: white; text-decoration: none;">Load More</p>
          </a>
        </div>
    </div>
</div>